### ISSUE TITLE
Tattered Cloth Recipe

### ISSUE THREAD

**Issue by vizthex123** [imkSushi/imkSushisMod#1]
I would say it should cost 1 Pre-Boss Loot Token per item, or give you 10 for 25 Tokens; since you need 10 for the battle standard and that's their only use.

**Comment by imkSushi** [comment]
This will no longer be relevant in v5.0.0, as I'm removing tokens

**Comment by vizthex123** [comment]
oof, ah well

**Comment by imkSushi** [comment]
I should probably either make the Tattered Cloth craftable, or up the Goblin Scout spawn rate though

**Comment by vizthex123** [comment]
Yeah, and have a config for either. Would be noice.
