### ISSUE TITLE
Port to 1.4?

### ISSUE THREAD

**Issue by SreeVathsan32** [imkSushi/imkSushisMod#2]
Will the mod be ported over to 1.4?

**Comment by imkSushi** [comment]
I refer you to this post:

https://forums.terraria.org/index.php?threads/imksushis-mod.34233/post-2734648


Additionally:
a) You shouldn't go around asking modders that. They'll get round to it when they get round to it. It's simply rude to ask.
b) Even if you were to ask, do it via Discord pm or Discord server or TCF pm or whatever. Either way, this isn't the place to ask either.
